// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.8.0
// source: vogelnest-data.proto

package schema

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Tweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates       *Coordinates `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Id                int64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Lange             string       `protobuf:"bytes,3,opt,name=lange,proto3" json:"lange,omitempty"`
	PossibleSensitive bool         `protobuf:"varint,4,opt,name=possibleSensitive,proto3" json:"possibleSensitive,omitempty"`
	Stats             *TweetStats  `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	Witheld           *WitheldInfo `protobuf:"bytes,6,opt,name=witheld,proto3" json:"witheld,omitempty"`
	Retweet           *Tweet       `protobuf:"bytes,7,opt,name=retweet,proto3" json:"retweet,omitempty"`
	Text              string       `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	QuoteInfo         *QuoteInfo   `protobuf:"bytes,9,opt,name=quoteInfo,proto3" json:"quoteInfo,omitempty"`
	Entities          *Entities    `protobuf:"bytes,10,opt,name=entities,proto3" json:"entities,omitempty"`
	CreatedAt         string       `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Tweet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tweet) GetLange() string {
	if x != nil {
		return x.Lange
	}
	return ""
}

func (x *Tweet) GetPossibleSensitive() bool {
	if x != nil {
		return x.PossibleSensitive
	}
	return false
}

func (x *Tweet) GetStats() *TweetStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Tweet) GetWitheld() *WitheldInfo {
	if x != nil {
		return x.Witheld
	}
	return nil
}

func (x *Tweet) GetRetweet() *Tweet {
	if x != nil {
		return x.Retweet
	}
	return nil
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tweet) GetQuoteInfo() *QuoteInfo {
	if x != nil {
		return x.QuoteInfo
	}
	return nil
}

func (x *Tweet) GetEntities() *Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Tweet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Entities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtags []*Hashtag `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Urls     []*URLInfo `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	Media    []*Media   `protobuf:"bytes,3,rep,name=media,proto3" json:"media,omitempty"`
	Mentions []*Mention `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty"`
}

func (x *Entities) Reset() {
	*x = Entities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entities) ProtoMessage() {}

func (x *Entities) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entities.ProtoReflect.Descriptor instead.
func (*Entities) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{1}
}

func (x *Entities) GetHashtags() []*Hashtag {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *Entities) GetUrls() []*URLInfo {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Entities) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Entities) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type Hashtag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices *Indices `protobuf:"bytes,1,opt,name=indices,proto3" json:"indices,omitempty"`
	Text    string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Hashtag) Reset() {
	*x = Hashtag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashtag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashtag) ProtoMessage() {}

func (x *Hashtag) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashtag.ProtoReflect.Descriptor instead.
func (*Hashtag) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{2}
}

func (x *Hashtag) GetIndices() *Indices {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *Hashtag) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Indices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Indices) Reset() {
	*x = Indices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Indices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indices) ProtoMessage() {}

func (x *Indices) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indices.ProtoReflect.Descriptor instead.
func (*Indices) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{3}
}

func (x *Indices) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Indices) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url            *URLInfo    `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id             int64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	MediaURL       string      `protobuf:"bytes,3,opt,name=mediaURL,proto3" json:"mediaURL,omitempty"`
	MediaURLHttps  string      `protobuf:"bytes,4,opt,name=mediaURLHttps,proto3" json:"mediaURLHttps,omitempty"`
	SourceStatusID int64       `protobuf:"varint,5,opt,name=sourceStatusID,proto3" json:"sourceStatusID,omitempty"`
	Type           string      `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Size           *MediaSizes `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	VideoInfo      *VideoInfo  `protobuf:"bytes,8,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetUrl() *URLInfo {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetMediaURL() string {
	if x != nil {
		return x.MediaURL
	}
	return ""
}

func (x *Media) GetMediaURLHttps() string {
	if x != nil {
		return x.MediaURLHttps
	}
	return ""
}

func (x *Media) GetSourceStatusID() int64 {
	if x != nil {
		return x.SourceStatusID
	}
	return 0
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetSize() *MediaSizes {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Media) GetVideoInfo() *VideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

type MediaSizes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumb  *MediaSize `protobuf:"bytes,1,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Small  *MediaSize `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	Medium *MediaSize `protobuf:"bytes,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Large  *MediaSize `protobuf:"bytes,4,opt,name=large,proto3" json:"large,omitempty"`
}

func (x *MediaSizes) Reset() {
	*x = MediaSizes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaSizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSizes) ProtoMessage() {}

func (x *MediaSizes) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSizes.ProtoReflect.Descriptor instead.
func (*MediaSizes) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{5}
}

func (x *MediaSizes) GetThumb() *MediaSize {
	if x != nil {
		return x.Thumb
	}
	return nil
}

func (x *MediaSizes) GetSmall() *MediaSize {
	if x != nil {
		return x.Small
	}
	return nil
}

func (x *MediaSizes) GetMedium() *MediaSize {
	if x != nil {
		return x.Medium
	}
	return nil
}

func (x *MediaSizes) GetLarge() *MediaSize {
	if x != nil {
		return x.Large
	}
	return nil
}

type MediaSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  int32  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Resize string `protobuf:"bytes,3,opt,name=resize,proto3" json:"resize,omitempty"`
}

func (x *MediaSize) Reset() {
	*x = MediaSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSize) ProtoMessage() {}

func (x *MediaSize) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSize.ProtoReflect.Descriptor instead.
func (*MediaSize) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{6}
}

func (x *MediaSize) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaSize) GetResize() string {
	if x != nil {
		return x.Resize
	}
	return ""
}

type URLInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices     *Indices `protobuf:"bytes,1,opt,name=indices,proto3" json:"indices,omitempty"`
	DisplayURL  string   `protobuf:"bytes,2,opt,name=displayURL,proto3" json:"displayURL,omitempty"`
	ExpandedURL string   `protobuf:"bytes,3,opt,name=expandedURL,proto3" json:"expandedURL,omitempty"`
	Url         string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *URLInfo) Reset() {
	*x = URLInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLInfo) ProtoMessage() {}

func (x *URLInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLInfo.ProtoReflect.Descriptor instead.
func (*URLInfo) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{7}
}

func (x *URLInfo) GetIndices() *Indices {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *URLInfo) GetDisplayURL() string {
	if x != nil {
		return x.DisplayURL
	}
	return ""
}

func (x *URLInfo) GetExpandedURL() string {
	if x != nil {
		return x.ExpandedURL
	}
	return ""
}

func (x *URLInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Mention struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScreenName string `protobuf:"bytes,3,opt,name=screenName,proto3" json:"screenName,omitempty"`
}

func (x *Mention) Reset() {
	*x = Mention{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mention) ProtoMessage() {}

func (x *Mention) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mention.ProtoReflect.Descriptor instead.
func (*Mention) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{8}
}

func (x *Mention) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mention) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mention) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

type VideoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AspectRatio    *AspectRatio    `protobuf:"bytes,1,opt,name=aspectRatio,proto3" json:"aspectRatio,omitempty"`
	DurationMillis int32           `protobuf:"varint,2,opt,name=durationMillis,proto3" json:"durationMillis,omitempty"`
	Variants       []*VideoVariant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{9}
}

func (x *VideoInfo) GetAspectRatio() *AspectRatio {
	if x != nil {
		return x.AspectRatio
	}
	return nil
}

func (x *VideoInfo) GetDurationMillis() int32 {
	if x != nil {
		return x.DurationMillis
	}
	return 0
}

func (x *VideoInfo) GetVariants() []*VideoVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type VideoVariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Bitrate     int32  `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *VideoVariant) Reset() {
	*x = VideoVariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoVariant) ProtoMessage() {}

func (x *VideoVariant) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoVariant.ProtoReflect.Descriptor instead.
func (*VideoVariant) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{10}
}

func (x *VideoVariant) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *VideoVariant) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *VideoVariant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AspectRatio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  int32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *AspectRatio) Reset() {
	*x = AspectRatio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspectRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectRatio) ProtoMessage() {}

func (x *AspectRatio) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectRatio.ProtoReflect.Descriptor instead.
func (*AspectRatio) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{11}
}

func (x *AspectRatio) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AspectRatio) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QuoteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tweet *Tweet `protobuf:"bytes,2,opt,name=tweet,proto3" json:"tweet,omitempty"`
}

func (x *QuoteInfo) Reset() {
	*x = QuoteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteInfo) ProtoMessage() {}

func (x *QuoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteInfo.ProtoReflect.Descriptor instead.
func (*QuoteInfo) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{12}
}

func (x *QuoteInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuoteInfo) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type WitheldInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithheldCopyright   bool     `protobuf:"varint,1,opt,name=withheldCopyright,proto3" json:"withheldCopyright,omitempty"`
	WithheldScope       string   `protobuf:"bytes,2,opt,name=withheldScope,proto3" json:"withheldScope,omitempty"`
	WithheldInCountries []string `protobuf:"bytes,3,rep,name=withheldInCountries,proto3" json:"withheldInCountries,omitempty"`
}

func (x *WitheldInfo) Reset() {
	*x = WitheldInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WitheldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitheldInfo) ProtoMessage() {}

func (x *WitheldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitheldInfo.ProtoReflect.Descriptor instead.
func (*WitheldInfo) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{13}
}

func (x *WitheldInfo) GetWithheldCopyright() bool {
	if x != nil {
		return x.WithheldCopyright
	}
	return false
}

func (x *WitheldInfo) GetWithheldScope() string {
	if x != nil {
		return x.WithheldScope
	}
	return ""
}

func (x *WitheldInfo) GetWithheldInCountries() []string {
	if x != nil {
		return x.WithheldInCountries
	}
	return nil
}

type TweetStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuoteCount   int32 `protobuf:"varint,1,opt,name=quoteCount,proto3" json:"quoteCount,omitempty"`
	ReplyCount   int32 `protobuf:"varint,2,opt,name=replyCount,proto3" json:"replyCount,omitempty"`
	RetweetCount int32 `protobuf:"varint,3,opt,name=retweetCount,proto3" json:"retweetCount,omitempty"`
	Retweeted    bool  `protobuf:"varint,4,opt,name=retweeted,proto3" json:"retweeted,omitempty"`
}

func (x *TweetStats) Reset() {
	*x = TweetStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetStats) ProtoMessage() {}

func (x *TweetStats) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetStats.ProtoReflect.Descriptor instead.
func (*TweetStats) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{14}
}

func (x *TweetStats) GetQuoteCount() int32 {
	if x != nil {
		return x.QuoteCount
	}
	return 0
}

func (x *TweetStats) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *TweetStats) GetRetweetCount() int32 {
	if x != nil {
		return x.RetweetCount
	}
	return 0
}

func (x *TweetStats) GetRetweeted() bool {
	if x != nil {
		return x.Retweeted
	}
	return false
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat  float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	Type string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vogelnest_data_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_vogelnest_data_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_vogelnest_data_proto_rawDescGZIP(), []int{15}
}

func (x *Coordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinates) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *Coordinates) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_vogelnest_data_proto protoreflect.FileDescriptor

var file_vogelnest_data_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x6f, 0x67, 0x65, 0x6c, 0x6e, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfb, 0x02, 0x0a, 0x05, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x6f, 0x73, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x11, 0x70, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x07, 0x77, 0x69, 0x74, 0x68, 0x65,
	0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x65,
	0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x77, 0x69, 0x74, 0x68, 0x65, 0x6c, 0x64, 0x12,
	0x20, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x25, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x24, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x12, 0x24, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x07, 0x48, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x12, 0x22, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2d, 0x0a, 0x07,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x05,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x1a, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x52, 0x4c, 0x12, 0x24, 0x0a,
	0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x52, 0x4c, 0x48, 0x74, 0x74, 0x70, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x52, 0x4c, 0x48, 0x74,
	0x74, 0x70, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x28, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x53, 0x69, 0x7a, 0x65, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x20, 0x0a, 0x05, 0x73,
	0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x05, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x12, 0x22, 0x0a,
	0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x05, 0x6c, 0x61,
	0x72, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64,
	0x65, 0x64, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70,
	0x61, 0x6e, 0x64, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x4d, 0x0a, 0x07, 0x4d, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x09, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x0b, 0x61, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x52, 0x0b, 0x61, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12,
	0x29, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62,
	0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3b, 0x0a, 0x0b, 0x41, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x39, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x22, 0x93, 0x01, 0x0a, 0x0b, 0x57, 0x69, 0x74, 0x68, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x11, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x70, 0x79,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x77, 0x69, 0x74,
	0x68, 0x68, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64,
	0x49, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x13, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6e, 0x64, 0x72, 0x65, 0x62, 0x71, 0x2f, 0x76, 0x6f, 0x67, 0x65, 0x6c, 0x6e, 0x65, 0x73, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vogelnest_data_proto_rawDescOnce sync.Once
	file_vogelnest_data_proto_rawDescData = file_vogelnest_data_proto_rawDesc
)

func file_vogelnest_data_proto_rawDescGZIP() []byte {
	file_vogelnest_data_proto_rawDescOnce.Do(func() {
		file_vogelnest_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_vogelnest_data_proto_rawDescData)
	})
	return file_vogelnest_data_proto_rawDescData
}

var file_vogelnest_data_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_vogelnest_data_proto_goTypes = []interface{}{
	(*Tweet)(nil),        // 0: Tweet
	(*Entities)(nil),     // 1: Entities
	(*Hashtag)(nil),      // 2: Hashtag
	(*Indices)(nil),      // 3: Indices
	(*Media)(nil),        // 4: Media
	(*MediaSizes)(nil),   // 5: MediaSizes
	(*MediaSize)(nil),    // 6: MediaSize
	(*URLInfo)(nil),      // 7: URLInfo
	(*Mention)(nil),      // 8: Mention
	(*VideoInfo)(nil),    // 9: VideoInfo
	(*VideoVariant)(nil), // 10: VideoVariant
	(*AspectRatio)(nil),  // 11: AspectRatio
	(*QuoteInfo)(nil),    // 12: QuoteInfo
	(*WitheldInfo)(nil),  // 13: WitheldInfo
	(*TweetStats)(nil),   // 14: TweetStats
	(*Coordinates)(nil),  // 15: Coordinates
}
var file_vogelnest_data_proto_depIdxs = []int32{
	15, // 0: Tweet.coordinates:type_name -> Coordinates
	14, // 1: Tweet.stats:type_name -> TweetStats
	13, // 2: Tweet.witheld:type_name -> WitheldInfo
	0,  // 3: Tweet.retweet:type_name -> Tweet
	12, // 4: Tweet.quoteInfo:type_name -> QuoteInfo
	1,  // 5: Tweet.entities:type_name -> Entities
	2,  // 6: Entities.hashtags:type_name -> Hashtag
	7,  // 7: Entities.urls:type_name -> URLInfo
	4,  // 8: Entities.media:type_name -> Media
	8,  // 9: Entities.mentions:type_name -> Mention
	3,  // 10: Hashtag.indices:type_name -> Indices
	7,  // 11: Media.url:type_name -> URLInfo
	5,  // 12: Media.size:type_name -> MediaSizes
	9,  // 13: Media.videoInfo:type_name -> VideoInfo
	6,  // 14: MediaSizes.thumb:type_name -> MediaSize
	6,  // 15: MediaSizes.small:type_name -> MediaSize
	6,  // 16: MediaSizes.medium:type_name -> MediaSize
	6,  // 17: MediaSizes.large:type_name -> MediaSize
	3,  // 18: URLInfo.indices:type_name -> Indices
	11, // 19: VideoInfo.aspectRatio:type_name -> AspectRatio
	10, // 20: VideoInfo.variants:type_name -> VideoVariant
	0,  // 21: QuoteInfo.tweet:type_name -> Tweet
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_vogelnest_data_proto_init() }
func file_vogelnest_data_proto_init() {
	if File_vogelnest_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vogelnest_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashtag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Indices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaSizes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mention); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoVariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspectRatio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WitheldInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vogelnest_data_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vogelnest_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vogelnest_data_proto_goTypes,
		DependencyIndexes: file_vogelnest_data_proto_depIdxs,
		MessageInfos:      file_vogelnest_data_proto_msgTypes,
	}.Build()
	File_vogelnest_data_proto = out.File
	file_vogelnest_data_proto_rawDesc = nil
	file_vogelnest_data_proto_goTypes = nil
	file_vogelnest_data_proto_depIdxs = nil
}
